// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqfchplxfktbzblhzhnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZmNocGx4Zmt0YnpibGh6aG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDEzMTcsImV4cCI6MjA2NTExNzMxN30.2rg18Mbga8qL2QeDGtq199mOJaswgkC7UuxHZfFERak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);